# Generated by Django 6.0.6 on 2026-08-17 16:36

from django.db import migrations, models


def migrate_approved_instances(apps, schema_editor):
    WorkflowInstance = apps.get_model("workflow_instances", "WorkflowInstance")
    WorkflowInstance.objects.filter(status="APPROVED").update(status="COMPLETED")


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_instances', '0002_alter_workflowinstance_current_step'),
    ]

    operations = [
        migrations.RunPython(
            migrate_approved_instances,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
