# Generated by Django 6.0.6 on 2026-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_instances', '0003_alter_workflowinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='request_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
